# Moss — custom theme (dark green background)
foreground            #e6e1c5
background            #0e2009
cursor                #ae9184
selection_background  #1d3a13
selection_foreground  #e6e1c5
url_color             #7fa3b2

color0                #0a1606
color8                #4a4b3a
color1                #754043
color9                #cc0000
color2                #727359
color10               #d4cb92
color3                #8b6220
color11               #c98f2e
color4                #598392
color12               #7fa3b2
color5                #824c71
color13               #b07a9d
color6                #ae9184
color14               #d9c6b8
color7                #d4cb92
color15               #e6e1c5

active_tab_foreground   #e6e1c5
active_tab_background   #1d3a13
inactive_tab_foreground #727359
inactive_tab_background #0a1606
